# Generated by Django 5.1.3 on 2024-11-24 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=100, verbose_name='Status of the room type')),
            ],
            options={
                'verbose_name_plural': 'Room Types',
                'db_table': 'RoomType',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=100, verbose_name='Status of the room')),
                ('price', models.FloatField(default=0)),
                ('room_type', models.ForeignKey(db_column='room_type', on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='rooms.roomtype')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
