# Generated by Django 5.1.4 on 2025-01-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneous',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('maintenance', 'Maintenance'), ('servicing', 'Servicing'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
