# Generated by Django 5.1.3 on 2024-11-24 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('tax_percentage', models.FloatField(default=0)),
                ('amount_payed', models.FloatField(default=0)),
                ('amount_change', models.FloatField(default=0)),
                ('guest', models.ForeignKey(db_column='guest', on_delete=django.db.models.deletion.DO_NOTHING, to='guests.guest')),
            ],
            options={
                'db_table': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_detail', models.FloatField()),
                ('reservation', models.ForeignKey(db_column='reservation', on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.reservation')),
                ('room', models.ForeignKey(db_column='room', on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.room')),
            ],
            options={
                'db_table': 'ReservationDetails',
            },
        ),
    ]
