# Generated by Django 5.1.3 on 2024-11-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
