# Generated by Django 5.1.3 on 2024-11-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='Reservations',
        ),
    ]
