# Generated by Django 5.1.3 on 2024-11-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservationdetail_quantity_alter_reservation_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetail',
            old_name='quantity',
            new_name='days',
        ),
    ]
