# Generated by Django 5.1.4 on 2024-12-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('supplier_name', 'contact_info')},
        ),
    ]
