# Generated by Django 5.1.4 on 2024-12-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_supplier_supplier_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='category',
        ),
        migrations.AddField(
            model_name='purchase',
            name='category_name',
            field=models.CharField(default='Default Category', max_length=255),
        ),
    ]
