# Generated by Django 5.1.3 on 2024-12-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_name_product_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='product_name',
        ),
    ]
