# Generated by Django 5.1.4 on 2024-12-29 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_created_at_category_purchase_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UTILITY', 'Utility'), ('RENT', 'Rent'), ('SALARIES', 'Salaries'), ('OTHER', 'Other')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store_miscellaneous',
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
