# Generated by Django 5.1.3 on 2024-12-13 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_supplier_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'product')},
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(through='inventory.SupplierProduct', to='inventory.product'),
        ),
    ]
