# Generated by Django 5.1.3 on 2024-12-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_supplierproduct_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.AddField(
            model_name='supplier',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
    ]
