# Generated by Django 5.1.3 on 2024-12-14 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_purchase_product_alter_purchase_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cost',
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_purchases', to='inventory.supplier'),
        ),
    ]
