# Generated by Django 5.1.4 on 2025-01-03 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
