# Generated by Django 5.1.3 on 2024-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sales_tendered_amount_sales_amount_payed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
